adversarial_training:
  adversarial_data_dir: data/adversarial/iterative_training
  adversarial_ratio: 0.2
  convergence_threshold: 0.001
  max_iterations: 3
  save_adversarial_examples: true
  start_from_iteration: 0
attack_config: configs/attack_genetic.yaml
checkpointing:
  monitor_metric: val_accuracy
  save_best_only: true
  save_dir: models/adversarial_training
  save_frequency: 1
monitoring:
  log_level: INFO
  metrics_file: data/adversarial/iterative_training/training_metrics.csv
  plot_accuracy: true
  plot_dir: plots/adversarial_training
  save_metrics: true
output:
  generate_report: true
  results_dir: results/adversarial_training
  save_final_model: true
training:
  base_model: zhihan1996/DNABERT-2-117M
  batch_size: 16
  dataset: tf
  fine_tune: false
  learning_rate: 2.0e-05
  max_length: 200
  num_classes: 2
  num_epochs: 3
  seed: 42
  warmup_steps: 500
  weight_decay: 0.01
