attack:
  dataset: tf
  max_perturbations: 8
  name: genetic_algorithm
  target_model: zhihan1996/DNABERT-2-117M
  test_samples: 50
biological_constraints:
  avoid_stop_codons: true
  max_gc_deviation: 0.05
  prefer_transitions: true
  preserve_motifs: true
fitness:
  biological_penalty: 0.1
  confidence_drop_weight: 2.0
  perturbation_penalty: 0.05
genetic_algorithm:
  convergence_threshold: 20
  crossover_rate: 0.9
  elite_ratio: 0.1
  max_generations: 200
  mutation_rate: 0.3
  population_size: 100
output:
  detailed_logging: true
  output_dir: data/adversarial/genetic_attack
  save_adversarial_sequences: true
  save_attack_statistics: true
success_criteria:
  confidence_threshold: 0.4
  min_confidence_drop: 0.15
